# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c57bb443c9bcee2f09236fa3445d0b981c6f6ce9fff65640ad662762d338a4d7335c757e9dd3329dada79b379795ddb6c467ffd3841167e2fa811f53864c0ee3

test:
  secret_key_base: c2b054be51711c646f77ae24904f4bdc81f4d7db1e3b700e9b65b6c9ee2816b7e2afb3cae46461eedfcbac2b65df89e805b187ee37cf3446659a6205ce8cf7ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
