# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 467a6eff389fdfee2abed21d838dbb3b7e4420a15c4037d847401b93682cf0bde34dc057675fab3aa9fc44bec65cde9bc3323949291eedc5d8c28af1142f5405

test:
  secret_key_base: bffa79c1056258e45acd48bdd93e6615cb9b2ee3fdb24bf4b3f11746129057d0da65936eec7fab5e02d46b0307c5fc41f811f441a39e7b771adff0d2c25a12e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
