# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d700af207929e0a4435b52ff540c859dff119892cc57a3cf90112b9a7bc1011b5a5a3e13d6d235eceba9f7114e1a4918aa5375c3729f8b05921380e5085e534

test:
  secret_key_base: 158b970cb0019e09d34a5793ef89e7bad1cd187daf66ec0012306942dde6d1931547506dea663e9d97594f8ea0f2e0205a03013cca5cfa19a616ce45f5c096f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
