# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f65aad1eeb24214c44d60079d4323571890bc3a8d4ead749b9c4a38d97aab21bd288943fad606000fff3c9b332f6c4294eaf2654bb7a86d0176fd82483033da

test:
  secret_key_base: acd0d18ce885adadc09d8b7cab2fdd6d7f0285660a717c90929aed1f188ffb5c59cfe9bf402ba1261e5ffdc51ea9e1a604ef1578d96e12feed91cccea8ba6b23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
