DROP TABLE IF EXISTS jedis;

CREATE TABLE jedis (
  id serial PRIMARY KEY,
  name varchar(50) NOT NULL,
  lightsaber_color varchar(50) NOT NULL,
  years_training integer NOT NULL,
  tempted_by_dark_side boolean NOT NULL,
  temptation varchar(50) NOT NULL
);

INSERT INTO jedis (name, lightsaber_color, years_training, tempted_by_dark_side, temptation) VALUES
('James Lee', 'red', 5, true, 'miniature pigs'),
('Puneet Maskey', 'blue', 15, true, 'southern cooking'),
('Jonathan Guzman', 'green', 7, false, 'warm baked goods'),
('Xinke Li', 'teal', 12, true, 'jokes'),
('Mazhar Khan', 'black', 11, true, 'kittens'),
('Bairon Vasquez', 'purple', 9, false, 'cheesecake'),
('Laura Ayala', 'green', 12, true, 'thin crust pizza'),
('Carson Hyde', 'green', 1, true, 'hanson'),
('Miriam Hernandez', 'red', 5, true, 'cheap coffee'),
('Vanice Yee', 'orange', 18, false, 'pumpkin spice'),
('Justin Peck', 'purple', 7, false, 'ugg boots'),
('Justin Johnson', 'blue', 9, true, 'the LES'),
('Jayan Zaman', 'teal', 4, true, 'IPAs'),
('Bryan Buitrago', 'blue', 15, true, 'the phrase YOLO'),
('Emmanuel Paulino', 'green', 14, false, 'water polo'),
('Taj English', 'red', 11, true, 'whiskey gingers'),
('Glenn Basgaard', 'red', 10, true, 'cute old people'),
('Jennifer Christie', 'black', 10, true, 'broadway'),
('Ayo Wynter', 'blue', 7, true, 'dirty water dogs'),
('Taylor Halsted', 'blue', 9, false, '2pac vs biggie debates'),
('Leslie Behum', 'green', 1, false, 'candy cigarettes'),
('Fariha Kazi', 'teal', 3, false, 'sounds of the rainforest'),
('Daniel A Normandia', 'teal', 4, true, 'nutella'),
('Nick Costanzo', 'red', 8, true, 'SHOTS!'),
('Malik Wormsby', 'black', 15, false, 'ninjas'),
('Matthew Cabezon', 'orange', 18, false, 'david bowie impersonators'),
('Kristi Murphy', 'teal', 20, true, 'warm laundry'),
('Marcela Silva', 'red', 20, true, 'smell of gasoline'),
('Hillary Kane', 'red', 19, true, 'extra cheese pizza'),
('Connie Cheng', 'blue', 15, true, 'Jareds hair'),
('Miko Brandini', 'orange', 5, true, 'boybands'),
('Michael Rivera', 'green', 1, false, 'teddybears'),
('Robert Mathews', 'blue', 1, false, 'tequilla'),
('Danielle Twaalfhoven', 'purple', 12, true, 'puppy in a cup'),
('Michelle Brant', 'purple', 14, false, 'cheap beer'),
('Marcos Wade', 'red', 16, true, 'actual kryptonite'),
('Kasaun Fryson', 'blue', 3, false, 'video games'),
('Dominique Alexander', 'teal', 5, true, 'costume jewelry')

