# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 909b70d12918c8b6315c1777a77c40518024b35a28403a3288f6cffa90ca54729104f09e4c33845b838f8b191bef0e430a1ce7eecc6665384dec1606f4b19edd

test:
  secret_key_base: af3695ab6dcf898f373e0c30bc9a0184febfdf92e8ff6858cc9a0b89e447aafd29653054d1491bcde51b302a34ac0bbf8eaab4fbb5fb4b96a1812bd992c28b01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
